#!/bin/python

import urllib.request
import time
import sys
import datetime

if len(sys.argv) > 1 and sys.argv[1] == "-h":
  print("run with no arguments to start checking. run with -u to get a new copy before checking")
  exit()

if len(sys.argv) > 1 and sys.argv[1] == "-u":
  with open("webcopy.html", "wb") as f:
    Copy = urllib.request.urlopen("https://www.nomanssky.com/release-log").read()
    LineList = Copy.split(b'\n')
    NewList = []
    for i in range(len(LineList)):
      if b"<script" in LineList[i]:
        continue
      NewList.append(LineList[i])
    NewCopy = b""
    for i in range(len(NewList)):
      NewCopy += NewList[i] + b'\n'
    print("INFO: copy update requested")
    f.write(NewCopy)

try:
  Copy = urllib.request.urlopen("https://www.nomanssky.com/release-log").read()
  LineList = Copy.split(b'\n')
  NewList = []
  for i in range(len(LineList)):
    if b"<script" in LineList[i]:
      continue
    NewList.append(LineList[i])
  NewCopy = b""
  for i in range(len(NewList)):
    NewCopy += NewList[i] + b'\n'
  with open("webcopy.html", "rb") as f:
    OldCopy = f.read()
    while True:
      if NewCopy != OldCopy:
        break
      time.sleep(1)
      Copy = urllib.request.urlopen("https://www.nomanssky.com/release-log").read()
      LineList = Copy.split(b'\n')
      NewList = []
      for i in range(len(LineList)):
        if b"<script" in LineList[i]:
          continue
        NewList.append(LineList[i])
      NewCopy = b""
      for i in range(len(NewList)):
        NewCopy += NewList[i] + b'\n'
      ts = time.time()
      print(f"INFO: no change noticed - {datetime.datetime.fromtimestamp(ts).strftime('%m, %d - %H:%M:%S')}")

except FileNotFoundError:
  with open("webcopy.html", "wb") as f:
    print("WARN: no website copy found. creating one.")
    f.write(NewCopy)
  exit()

except KeyboardInterrupt:
  print("\nINFO: exiting")
  exit()

except Exception as e:
  print(f"ERROR: {e=}, {type(e)=}")
  exit()

with open("webcopy.html", "wb") as f:
  ts = time.time()
  for line in reversed(NewCopy.split(b"\n")):
    if b"<h2>" in line:
      nu = line.partition(b"</h2>")
  nu = str(nu[0]).replace("b'", "").replace("<h2>", "").strip().strip("'")
  print(f"\n---------------\nSUCCESS: website change noticed - {datetime.datetime.fromtimestamp(ts).strftime('%m, %d - %H:%M:%S')}")
  print(f"update name - {nu}")
  f.write(NewCopy)
